language: go

go:
- 1.13.4

install:
- true

env:
  global:
  - GO111MODULE=on
  - GOFLAGS="-mod=vendor"

script:
- go vet
- go test ./...
- go build -o dotenv
- "./dotenv --version"
- if [ -z "$TRAVIS_TAG" ]; then exit 0; else
  GOOS=linux go build -a -tags netgo -ldflags "-s -w -X main.version=$TRAVIS_TAG" -o binaries/dotenv_linux &&
  GOOS=darwin go build -a -tags netgo -ldflags "-s -w -X main.version=$TRAVIS_TAG" -o binaries/dotenv_darwin ;
  fi

deploy:
  provider: releases
  api_key:
    secure: nZ4h6NJad5EP85TOeptQG9cEa5G//33kF4n+pZqkpasWJkOKG+/BlE3XuzGBj8683NNzuXLoY+9ZRLFnuigrKQEnlVhMvZEbgCq5j2Gdvi26rtF4uUMsGCs3Hj7tP1fucXm/y2R2/vkrWJIoKxDiOz1xE7894rk5yf3wrAiorVzTk9Zse8dC0WKJqh1oEk7A3vAols5u2IeFDVwn8bI68MjM25gjfh8tFaClD6SJtA3lR3Z5/viAqg3ud4FeHNKymQ6dDQaE/AGsWUgGj7lrIUMOq3dl7bfqJyXqOG7DpMDtMrWv6xfycYV52ycTfXW2xbaKCrgZjqZQtGIOYICWxI2bbzI8XV7tM0mmwujELhfJn+fWxdqMbcF21/npQvDXnrULfyzKjAxyI4AJjSU1Ttrm5LXjYecoy1bqRQxGp2UhStPwMBRMuMeSvM/i7vd9vpPVnZh+JXKKBp2sG3YfNGNkjSUFwaIIqLL1iinwOAobpfTzqBugFBFJmFhndZ67VW6psKHqR68ouIdPr+FdkmVKD5atbA608aPX2Eem2603Njeg0WqRTmy4GXdPrpVG2WxhXnChT/ys5f/S0DWY6XydXjLnl2u0VTGpteAaJMFsmfbugGAlAHWhIiF4yp84j1p1fnr5wigd/JBM2Bd2IFL8s6o5owPyvYh4jGIut5Y=
  file_glob: true
  file: binaries/*
  skip_cleanup: true
  on:
    tags: true
