[package]
name = "dotenv"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
rustix = { version = "0.38.42", features = ["process"] }
tempfile = "3.14.0"
which = "7.0.0"

[profile.release]
opt-level = "z"   # Optimize for size.
lto = true        # Enable link time optimization.
codegen-units = 1 # Reduce parallel code generation units.
