[package]
name = "dotenv"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
libc = "0.2.168"
tempfile = "3.14.0"
which = "7.0.0"

[profile.release]
opt-level = "z"   # Optimize for size.
lto = true        # Enable link time optimization.
codegen-units = 1 # Reduce parallel code generation units.
strip = "symbols" # Strip debug symbols.
